### ISSUE TITLE
Project TODO

### ISSUE THREAD

**Issue by mmphego** [PrincePhate/First-Project-Calculator-#1]
As part of your mentorship, I would like to propose the following challenges that you have to undergo. This will take you from beginner to intermediate level. 
When in doubt Google, if you have any questions reach out to me!

**DO NOT COPY AND PASTE**

**Note:** Every bullet point should be accompanied by a Pull Request, when the PR is merged then you can [x] check bullet point.

- [x] Rename Python script to `calculator.py` for readability
- [x] Update `README.md` - About what the project is all about
- [ ] Refactor the script and convert logic to functions.
    - Expectations: 
```python
def calculate(x, y, op):
    pass

value = calculate(1, 3, '+')
print(value)
```

- [ ] Modularize the script i.e. `if __name__ == '__main__'`: https://www.freecodecamp.org/news/if-name-main-python-example/
- [ ] Parse arguments from CLI : https://stackoverflow.com/questions/20063/whats-the-best-way-to-parse-command-line-arguments
  - Expected outcome: `python calculator.py 2 + 5` or `python calculator.py add 2 5`
- [ ] Add tests using unittest/pytest module.
- [ ] Refactor code and also add error handling: read this [blogpost](https://dev.to/renegadecoder94/8-coolest-python-programming-language-features-58i9) for ideas
- [ ] Update tests to handle refactored code.
- [ ] Convert functions to class, for example `class Calculator:`
- [ ] Refactor application to use [SOLID Principles of Object Orianted Programming](https://realpython.com/solid-principles-python/)
- [ ] Add CI/CD either GitHub Actions or Circle CI. Read: https://www.youtube.com/playlist?list=PLArH6NjfKsUhvGHrpag7SuPumMzQRhUKY
- [ ] Containerize the package with Docker.
- [ ] Convert script to RESTful API
- [ ] Convert script to a Python package.
- [ ] Deploy to GitHub Pages

**Comment by mmphego** [comment]
> As part of your mentorship, I would like to propose the following challenges that you have to undergo. This will take you from beginner to intermediate level. When in doubt Google, if you have any questions reach out to me!
> 
> **DO NOT COPY AND PASTE**
> 
> **Note:** Every bullet point should be accompanied by a Pull Request, when the PR is merged then you can [x] check bullet point.
> 
> * [x]  Update `README.md` - About what the project is all about
> * [x]  Refactor the script and convert logic to functions.

Only [x] check the issue, once the PR has been merged!
